namespace: host_uk
name: cloudns
version: 1.1.0
readme: README.md
authors:
  - Jules
description: Ansible collection for ClouDNS DNS and Monitoring using Swagger/OpenAPI client.
license:
  - MIT
tags:
  - dns
  - cloudns
  - monitoring
  - swagger
  - openapi
repository: http://github.com/host-uk/ansible-cloudns
